files:
  - source: /xml/**/*.xml
    translation: /translations/%two_letters_code%/xml/**/%original_file_name%
    content_segmentation: 0
    translatable_elements:
      - /BMD
      - /BMD/Speakers
      - /BMD/Speakers/Speaker
      - /BMD/Dialog
      - /BMD/Dialog/Page
      - /BMD/Dialog/Option
  - source: /dt_xml/**/*.xml
    translation: /translations/%two_letters_code%/dt_xml/**/%original_file_name%
    content_segmentation: 0
    translatable_elements:
      - /P3RDataTableText
      - /P3RDataTableText/Text
      - /P3RDataTableText/Text/Translation
      - /P3RDataTableFStrings
      - /P3RDataTableFStrings/String
      - /P3RDataTableFStrings/String/Translation
