<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>P3RPlgTool</AssemblyName>
    <Version>0.2.0</Version>
    <Authors>KartinX</Authors>
    <Description>Persona 3 Reload PLG inspection and patch helper.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="D:\Modding\Forcodex\FModel\CUE4Parse\CUE4Parse\CUE4Parse.csproj" />
  </ItemGroup>

</Project>


